// Complete Bad Bunny Discography - 212 songs from user's CSV
const mockBadBunnySongs = [
  { id: 1, name: "NI BIEN NI MAL", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 2, name: "200 Mph", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 3, name: "Quien Tu Eres", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 4, name: "Caro", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 5, name: "Tenemos Que Hablar", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 6, name: "Otra Noche en Miami", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 7, name: "Ser Bichote", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 8, name: "Si Estuviesemos Juntos", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 9, name: "Solo de Mi", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 10, name: "Cuando Perriabas", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 11, name: "La Romana", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 12, name: "Como Antes", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 13, name: "RLNDT", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 14, name: "Estamos Bien", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 15, name: "MIA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 16, name: "MOJAITA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 17, name: "YO LE LLEGO", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 18, name: "CUIDADO POR AHI", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 19, name: "QUE PRETENDES", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 20, name: "LA CANCION", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 21, name: "UN PESO", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 22, name: "ODIO", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 23, name: "COMO UN BEBE", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 24, name: "Si Veo a Tu Mama", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 25, name: "La Dificil", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 26, name: "Pero Ya No", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 27, name: "La Santa", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 28, name: "Yo perreo Sola", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 29, name: "Bichiyal", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 30, name: "Solia", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 31, name: "La Zona", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 32, name: "Que Malo", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 33, name: "Vete", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 34, name: "Ignorantes", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 35, name: "A Tu Merced", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 36, name: "Una Vez", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 37, name: "Safaera", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 38, name: "25/8", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 39, name: "Esta Cabron Ser Yo", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 40, name: "Puesto Pa Guerrial", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 41, name: "P FKN R", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 42, name: "Hablamos Manana", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 43, name: "<3", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 44, name: "SI ELLA SALE", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 45, name: "MAS DE UNA CITA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 46, name: "BYE ME FUI", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 47, name: "CANCION CON YANDEL", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 48, name: "PA ROMPERLA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 49, name: "BAD CON NICKY", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 50, name: "BENDICIONES", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 51, name: "COMO SE SIENTE - Remix", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 52, name: "RONCA FREESTYLE", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 53, name: "EN CASITA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 54, name: "EL MUNDO ES MIO", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 55, name: "TE MUDASTE", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 56, name: "HOY COBRE", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 57, name: "MALDITA POBREZA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 58, name: "LA NOCHE DE ANOCHE", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 59, name: "TE DESEO LO MEJOR", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 60, name: "YO VISTO ASI", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 61, name: "HACIENDO QUE ME AMAS", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 62, name: "BOOKER T", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 63, name: "LA DROGA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 64, name: "DAKITI", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 65, name: "TRELLAS", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 66, name: "SORRY PAPI", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 67, name: "120", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 68, name: "ANTES QUE SE ACABE", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 69, name: "CANTARES DE NAVIDAD", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 70, name: "Moscow Mukle", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 71, name: "Despues de la Playa", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 72, name: "Me Porto Bonito", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 73, name: "Titi Me Pregunto", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 74, name: "Un Ratito", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 75, name: "Yo No Soy Celoso", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 76, name: "Tarot", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 77, name: "Neverita", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 78, name: "La Corriente", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 79, name: "Efecto", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 80, name: "Party", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 81, name: "Aguacero", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 82, name: "Ensename a Bailar", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 83, name: "Ojitos Lindos", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 84, name: "Dos Mil 16", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 85, name: "El Apagon", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 86, name: "Otro Atardecer", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 87, name: "Un Coco", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 88, name: "Andrea", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 89, name: "Me Fui de Vacaciones", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 90, name: "Un Verano Sin Ti", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 91, name: "Agosto", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 92, name: "Callaita", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 93, name: "NADIE SABE", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 94, name: "MONACO", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 95, name: "FINA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 96, name: "HIBIKI", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 97, name: "MR. OCTOBER", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 98, name: "CYBERTRUCK", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 99, name: "VOU 787", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 100, name: "SEDA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 101, name: "GRACIAS POR NADA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 102, name: "TELEFONO NUEVO", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 103, name: "BABY NUEVA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 104, name: "MERCEDES CAROTA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 105, name: "LOS PITS", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 106, name: "VUELVE CANDY B", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 107, name: "BATICANO", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 108, name: "NO ME QUIERO CASAR", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 109, name: "WHERE SHE GOES", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 110, name: "THUNDER LIGHTNING", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 111, name: "PERRO NEGRO", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 112, name: "EUROPA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 113, name: "ACHO PR", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 114, name: "UN PREVIEW", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 115, name: "NUEVAYoL", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 116, name: "VOY A LLeVARTE PA PR", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 117, name: "BAILE INoLVIDABLE", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 118, name: "PERFuMITO NUEVO", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 119, name: "WELTiTA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 120, name: "VeLDA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 121, name: "EL CLuB", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 122, name: "KETU TeCRE", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 123, name: "BOKeTE", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 124, name: "KLOuFRENS", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 125, name: "TURiSTA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 126, name: "CAFe CON RON", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 127, name: "PIToRRO DE COCO", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 128, name: "LO QUE LE PASO A HAWAii", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 129, name: "EoO", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 130, name: "DtMF", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 131, name: "LA MuDANZA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 132, name: "Otra Vez", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 133, name: "Diles", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 134, name: "Tu No Vive Asi", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 135, name: "Soy Peor", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 136, name: "Caile", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 137, name: "Pa Ti", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 138, name: "Crecia", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 139, name: "Amigos y Enemigos Remix", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 140, name: "Me Llueven 2", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 141, name: "Me Llueven 3.o", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 142, name: "No Te Hagas", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 143, name: "Tranquilo", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 144, name: "Trepate", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 145, name: "Me Mata", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 146, name: "Blockia", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 147, name: "Ahora Me Llama", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 148, name: "Un Ratito Mas", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 149, name: "Soy Peor Remix", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 150, name: "Demonia Baila", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 151, name: "Give It Up", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 152, name: "Netflixxx", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 153, name: "Tu No Metes Cabra", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 154, name: "Mayores", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 155, name: "Me Llueven Extenden Version", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 156, name: "Panamera Remix", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 157, name: "Bailame Remix", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 158, name: "Lean", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 159, name: "Mayores Urban Tropical", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 160, name: "Vuelve", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 161, name: "Ahora Me Llama Remix", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 162, name: "Tu No Metes Cabra Remix", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 163, name: "Krippy Kush", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 164, name: "Chambea", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 165, name: "Favorito De Los Capo Remix", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 166, name: "Amantes de una Noche", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 167, name: "El Combo Me Llama 2", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 168, name: "Fantasia", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 169, name: "Amorfoda", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 170, name: "Dime Si Te Acuerdas", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 171, name: "Loca Remix", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 172, name: "Deime", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 173, name: "Explicale", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 174, name: "Te Bote", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 175, name: "Te Descuido", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 176, name: "I Like It", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 177, name: "Original", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 178, name: "Satisfaccion", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 179, name: "Cual Es Tu Plan", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 180, name: "Vamos Pa la Calle", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 181, name: "Como Soy", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 182, name: "Esta Rico", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 183, name: "MIA feat Drake", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 184, name: "Te Guste", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 185, name: "LOYAL", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 186, name: "COMO SE SIENTE", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 187, name: "UN DIA ONE DAY", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 188, name: "Yo Perreo Sola Remix", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 189, name: "100 MILLONES", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 190, name: "Yonaguni", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 191, name: "AM Remix", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 192, name: "De Museo", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 193, name: "Volando Remix", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 194, name: "Volvi", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 195, name: "Lo Siento BB", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 196, name: "La Jumpa", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 197, name: "Gato de Noche", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 198, name: "un x100to", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 199, name: "K-POP", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 200, name: "ADIVINO", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 201, name: "Una Velita", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 202, name: "Que Pasaria", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 203, name: "ALAMBRE PuA", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 204, name: "Soltera Remix", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 205, name: "No Me Conoce Remix", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 206, name: "Estamos Arriba", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 207, name: "Bellacoso", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 208, name: "Kemba Walker", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 209, name: "Subimos de Rango", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 210, name: "Soy El Diablo Remix", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 211, name: "Cantalo", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" },
  { id: 212, name: "MOJABI GHOST", artist: "Bad Bunny", album: "YHLQMDLG", albumCover: "" }
];

module.exports = mockBadBunnySongs;
